### ISSUE TITLE
Pushpin adds source=Pushpin on all POIs

### ISSUE THREAD

**Issue by Zverik** [pushpin/pushpinosm.org#1]
Source tag is for the information source, i.e. survey, government data, satellite imagery, local knowledge, friends etc. Not for the editor or author information — those should go in the changeset tags. Pushpin already adds created_by tag to changesets, so no additional actions needed.

Just please do not add source=\* tags on POI. Changeset's created_by is enough. If you can't help it, use "survey" for a value.

**Comment by zhm** [comment]
Thanks for the feedback! I will get this fixed for the next version.

**Comment by colemanm** [comment]
We could make this a user-editable tag, rather than autofilled, and leave the "Pushpin" part in the changeset `created_by` tag. That way as the user you could optionally enter "local knowledge", "field survey", et cetera, if desired.

**Comment by Zverik** [comment]
Yes, that's an option. But considering the application, I doubt there would be any values besides `survey` :)

**Comment by zhm** [comment]
I removed the source=Pushpin logic. The source field will now be editable. Although technically sound to have that data on the changeset, it doesn't work very well in practice when you actually want to _use_ that data. i.e. making a "show me everything edited with JOSM in this area" isn't very easy to do. You have to be able to query by changeset, which isn't possible with the downstream API's (XAPI, Overpass). So you're left with running your own server :-/

**Comment by Zverik** [comment]
I've added [editor filter](http://zverik.osm.rambler.ru/whodidit/?zoom=12&lat=51.49355&lon=-0.11933&layers=BTT&editor=Pushpin&age=31) to whodidit project. The server is slow at the moment (queries take 30-60 seconds to complete), but I'm told it will be fixed soon.

**Comment by zhm** [comment]
@Zverik, that's awesome, I will check that out. Thanks!

**Comment by cquest** [comment]
The created_by tag on objects is deprecated but could be temporarily used to track pushpin edits...

**Comment by zhm** [comment]
This is now fixed in version 1.1 in the App Store. The app does not put any references to Pushpin on anything except the created_by key on the changeset.
