### ISSUE TITLE
Posting edits to Twitter

### ISSUE THREAD

**Issue by zhm** [pushpin/pushpinosm.org#6]
Sometimes the URL shows up as (null). It doesn't happen every time, so there's some kind of bug where the id of the node isn't being properly updated.

**Comment by harry-wood** [comment]
yeah. saw a tweet like this just now: https://twitter.com/MoiArcSan/statuses/260733964552114177

**Comment by zhm** [comment]
This is resolved in the 1.1 update that's now in the App Store
